Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,9 +26,8 @@ jobs:
       run: |
         git add debian-mirrors/debian-mirrors.txt
         git commit -m "Update Debian Mirror list" -a || echo "No changes to commit"
-        git push origin main
+        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
 
-        
   ubuntu-mirrors:
     runs-on: ubuntu-latest
     steps:
@@ -50,4 +49,4 @@ jobs:
       run: |
         git add ubuntu-mirrors/ubuntu-mirrors.txt
         git commit -m "Update Ubuntu Mirror list" -a || echo "No changes to commit"
-        git push origin main
+        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
