Update main.yml
only commit and push if file has changed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,13 +20,21 @@ jobs:
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git pull origin main
+    - name: Generate hash before changes
+      run: sha256sum debian-mirrors/debian-mirrors.txt > before.txt
     - name: Run fetcher script and generate EDL
       run: python debian-mirrors/debian-mirrors.py
+    - name: Generate hash after changes
+      run: sha256sum debian-mirrors/debian-mirrors.txt > after.txt
     - name: Commit and push if changes
       run: |
-        git add debian-mirrors/debian-mirrors.txt
-        git commit -m "Update Debian Mirror list" -a || echo "No changes to commit"
-        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
+        if cmp -s before.txt after.txt; then
+          echo "No changes to commit"
+        else
+          git add debian-mirrors/debian-mirrors.txt
+          git commit -m "Update Debian Mirror list" -a
+          git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
+        fi
 
   ubuntu-mirrors:
     runs-on: ubuntu-latest
@@ -43,10 +51,18 @@ jobs:
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git pull origin main
+    - name: Generate hash before changes
+      run: sha256sum ubuntu-mirrors/ubuntu-mirrors.txt > before.txt
     - name: Run fetcher script and generate EDL
       run: python ubuntu-mirrors/ubuntu-mirrors.py
+    - name: Generate hash after changes
+      run: sha256sum ubuntu-mirrors/ubuntu-mirrors.txt > after.txt
     - name: Commit and push if changes
       run: |
-        git add ubuntu-mirrors/ubuntu-mirrors.txt
-        git commit -m "Update Ubuntu Mirror list" -a || echo "No changes to commit"
-        git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
+        if cmp -s before.txt after.txt; then
+          echo "No changes to commit"
+        else
+          git add ubuntu-mirrors/ubuntu-mirrors.txt
+          git commit -m "Update Ubuntu Mirror list" -a
+          git push origin main || echo "Push failed, retrying..." && git pull --rebase origin main && git push origin main
+        fi
